CREATE TABLE IF NOT EXISTS Entities (
    id NVARCHAR(256) NOT NULL PRIMARY KEY,
    type TEXT NOT NULL,
    version INT NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS Events (
    entity_id NVARCHAR(256) NOT NULL,
    name TEXT NOT NULL,
    details TEXT NOT NULL,
    actor TEXT NOT NULL,
    timestamp DECIMAL(12,7) NOT NULL DEFAULT (UNIX_TIMESTAMP() / 86400),
    ordinal INT NOT NULL,
    position BIGINT NOT NULL
);
