<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <OutputType>Library</OutputType>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <PackageVersion>0.0.1</PackageVersion>
    <IsPackable>true</IsPackable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="schema.sql" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="8.0.10" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Segerfeldt.EventStore.Source\Segerfeldt.EventStore.Source.csproj" />
  </ItemGroup>

</Project>
