<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <OutputType>Library</OutputType>

        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageVersion>0.0.12</PackageVersion>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <ItemGroup>
      <PackageReference Include="Swashbuckle.AspNetCore.SwaggerGen" Version="6.8.1" />
    </ItemGroup>

    <ItemGroup>
      <None Include="README.md" Pack="true" PackagePath=""/>
      <Compile Include="..\Segerfeldt.EventStore.Shared\JSON.cs">
        <Link>Shared/JSON.cs</Link>
      </Compile>
    </ItemGroup>

</Project>
