<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <OutputType>Library</OutputType>

        <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
        <PackageReadmeFile>README.md</PackageReadmeFile>
        <PackageVersion>0.0.3</PackageVersion>
        <IsPackable>true</IsPackable>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" Version="8.0.10" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="$(SolutionDir)\Segerfeldt.EventStore.Projection\Segerfeldt.EventStore.Projection.csproj" />
    </ItemGroup>

    <ItemGroup>
      <None Include="README.md" Pack="true" PackagePath=""/>
      <Compile Include="$(SolutionDir)\Segerfeldt.EventStore.Shared\JSON.cs">
        <Link>JSON.cs</Link>
      </Compile>
    </ItemGroup>

</Project>
